include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance optimizations
    use_build_context_synchronously: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    prefer_if_null_operators: true
    prefer_spread_collections: true
    prefer_collection_literals: true
    sort_child_properties_last: true
